AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false
